### ISSUE TITLE
No connection to beacon with Altme possible. Im using an android phone and the tezos Ghostnet 

### ISSUE THREAD

**Issue by jtdemer** [TalaoDAO/AltMe#2349]
Since last Thursday it isn't possible to connect with Altme and beacon.

I tried it here:
https://faucet.ghostnet.teztnets.com/

And here:
https://identity.ascs.digital/

There is nothing happen at all while I want to connect. Neither on the browser or on the smartphone.

I'm using an Android phone with the latest Altme update 2.2.14 (One Ui 6.0 and Android 14).

I think the Ghostnet from tezos moved, could the issue relate to that?

**Comment by hawkbee1** [comment]
That's strange. Yesterday I had issues when testing but not today, everything works fine.

About yesterday: Both sites where failing because I had reset my wallet since previous attempt AND websites didn't present me a way to forget old connection. I was working fine in to cases: 
- when using anonymous navigation on the desktop
- After restoring my wallet from previous connection (last week) 

I don't see any issue on the wallet side here.
