### ISSUE TITLE
Add new switch in OIDC4VC settings "OIDC4VCI Proof Type'

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#2383]
it is a select between 2 values :  **jwt** by default or, **ldp_vp**
there will be later a 3rd value

in the wallet provider configuration the parameter is `proofType`

wording of the switch : 
 
OIDC4VCI Proof Type
jwt by default

**This option must be positionned after the VC Format in the menu**  

if option is jwt, no change to calculate the proof and add eth proof to the credential request

if option is ldp_vp, the proof is calculated with **didkit.did_auth** with the did:key of the wallet 
to add challenge and domain to the didkit.did_auth function , it needs to add an option 
example (python) : 
```

option = json.dumps({
        "challenge": "<nonce>",
        "domain": "<issuer>"
    })  
proof = await didkit.did_auth(did_wallet, option, key_wallet)
```

the challenge must be the nonce of the token endpoint, the domain must be the issuer

example of the `proof `to add in the credential request, the `proof_type `is "ldp_vp"

```
{
  "proof_type": "ldp_vp",
  "ldp_vp": {
       "@context": [
         "https://www.w3.org/2018/credentials/v1"
       ],
      "type": "VerifiablePresentation",
       "proof": {
           "@context": [
               "https://w3id.org/security/suites/jws-2020/v1"
            ],
            "type": "JsonWebSignature2020",
            "proofPurpose": "authentication",
           "verificationMethod":   "did:key:zDnaeUMik4FncK7HYNToFhZweFmc1qiT1ogvQWMFNvqazApbG#zDnaeUMik4FncK7HYNToFhZweFmc1qiT1ogvQWMFNvqazApbG",
            "created": "2024-02-11T13:04:17.670Z",
             "challenge": "<nonce>",
             "domain": "<issuer>",
           "jws":      "eyJhbGciOiJFUzI1NiIsImNyaXQiOlsiYjY0Il0sImI2NCI6ZmFsc2V9..9rRaLAImUUGv3pTEHX_AollU7ggJeb194LqfIoTm7F7iP4qRim7-tC0YcKy8fHHDYEejNajOUx5Tk4D5jN9J_Q"
  },
          "holder": "did:key:zDnaeUMik4FncK7HYNToFhZweFmc1qiT1ogvQWMFNvqazApbG"
      }
}
```

**Comment by hawkbee1** [comment]
Thierry Thevenet
  [08:48](https://talao.slack.com/archives/C03V9HU19DM/p1709279290225779)
i dont know your code but yes it looks like that.
didkit.did_auth needs options for challenge and domain and that is important
New
[08:52](https://talao.slack.com/archives/C03V9HU19DM/p1709279520934689)
[@Bibash Shrestha](https://talao.slack.com/team/U03025KCQ82)

specs about the ldp_proof/
proof: REQUIRED. The proof body of a W3C Verifiable Presentation.
domain: REQUIRED (string). The value of this claim MUST be the Credential Issuer Identifier.
challenge: REQUIRED when the Credential Issuer has provided a c_nonce. It MUST NOT be used otherwise. String, where the value is a server-provided c_nonce. It MUST be present when the Wallet received a server-provided c_nonce.
[08:52](https://talao.slack.com/archives/C03V9HU19DM/p1709279555744009)
domain and challe,nge are passed as option in didkit
