### ISSUE TITLE
When you click on the "SCAN" button and then cancel action, there is a "do you trust this host" message that appears on the screen

### ISSUE THREAD

**Issue by HugoNDO** [TalaoDAO/AltMe#607]
"Do you trust this host" is not needed here

**Comment by hawkbee1** [comment]
Probably due to new scan package integration.
![Screenshot_20220826-121326](https://user-images.githubusercontent.com/49282360/186882813-b2febb51-d122-456a-ba28-8c3ad701bec6.png)
![Screenshot_20220826-121331](https://user-images.githubusercontent.com/49282360/186882824-897786bb-6ead-4beb-9bbb-88a0cd6c4ab6.png)

**Comment by hawkbee1** [comment]
@bibash28 
Solving this ticket should remove this bug: https://github.com/TalaoDAO/AltMe/issues/608
