### ISSUE TITLE
Build of project

### ISSUE THREAD

**Issue by SteveDevs** [TalaoDAO/AltMe#971]
When trying to run flutter pub get. it throws the error:

"Because every version of did_kit from path depends on didkit from path which is forbidden, did_kit from path is forbidden.
So, because altme depends on did_kit from path, version solving failed.
Running "flutter pub get" in AltMe...                                   
pub get failed (66; So, because altme depends on did_kit from path, version solving failed.)"

**Comment by hawkbee1** [comment]
I see we lost some information along the road.
In order to use the app you need to build the didKit Package which is required. You can find instructions on building DIDKit on the original project: https://github.com/spruceid/credible. Currently we can't build DIDKit for android on apple M1 computer.

**Comment by SteveDevs** [comment]
> I see we lost some information along the road. In order to use the app you need to build the didKit Package which is required. You can find instructions on building DIDKit on the original project: https://github.com/spruceid/credible. Currently we can't build DIDKit for android on apple M1 computer.

Thanks worked, but still having build problems
