### ISSUE TITLE
Email proof check

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/AltMe#974]
When user get a new emailproof withe the same email as a pevious vc with same email then remove the previous vc

**Comment by bibash28** [comment]
Size: S

**Comment by ThierryThevenet** [comment]
Impossible to add an email proof !

**Comment by hawkbee1** [comment]
Why the revert: When adding EmailPass credential, the same credential is removed at the end of the process because removal is happening to late.

**Removal code**
![image](https://user-images.githubusercontent.com/49282360/201920891-1afa0d4c-f673-4e18-b6a8-46bf15fa0ffc.png)

**Which is called from wallet cubit which has already added the credential in the repository**
![image](https://user-images.githubusercontent.com/49282360/201921462-f3856804-b72d-413a-9b49-fe3f07c6ef35.png)
